services:
  - type: web
    name: apollo-filter-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash run.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
